# Generated by Django 5.1 on 2024-08-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_card_date_updated_alter_card_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
